name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ERICSANTANA10

          # CORES PERSONALIZADAS (AQUI ESTÁ O SEGREDO)
          color_snake: "#00ffff"        # cobrinha neon
          color_dots: "#003333,#005555,#008888,#00ffff,#66ffff"

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
