name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *" # Roda a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pacman-report
        uses: lowlighter/metrics@latest
        with:
          filename: pacman.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Deploy to Output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: output
          keep_files: true # ISSO impede que o arquivo suma
